### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by natashawatkins** [EconForge/interpolation.py#32]
Currently trying to switch `np.interp` to `interp`, and running into some stability issues - sometimes it works but sometimes I run into this error and my code won't work

<img width="854" alt="screen shot 2018-10-02 at 12 05 29 pm" src="https://user-images.githubusercontent.com/21038129/46362985-b95e3b80-c63f-11e8-849f-5a6c6c67cf3c.png">

**Comment by albop** [comment]
That suspiciously like the bug related to extrapolation that I fixed recently. Which version are you running ?

**Comment by albop** [comment]
If the problem is not with library version this issue is a bit hard for me to address as I have no idea what triggers the faulty behaviour. I would need a reduced example or at least some code that I can run.

**Comment by natashawatkins** [comment]
Yep I just uninstalled and then reinstalled and I'm still having issues

**Comment by albop** [comment]
I can't replicate it on my computers. Could you do the following please ?
- `conda remove interpolation`
- uninstall pip version by typing `pip uninstall interpolation` and repeat the operation twice
- `conda install interpolation`
Then if it still doesn't work, can you send me an example of faulty code ? Are you doing 1d, 2d, or higher dimension interpolation ?

**Comment by natashawatkins** [comment]
Do you mean `pip install interpolation`? I'm almost very sure I have 2.0.1 installed. It only occurs with this specific piece of code I'm using

**Comment by natashawatkins** [comment]
Here is the issue again after reinstalling:

**Comment by albop** [comment]
No, I mean  `pip uninstall ...`. Sometimes an old pip version can cohabitate with the conda version.

**Comment by albop** [comment]
hmm, I don't see the issue ;-)

**Comment by natashawatkins** [comment]
I did pip uninstall but I couldn't find the conda package? Am I meant to have a channel configured or something?

**Comment by albop** [comment]
sorry, should have specified it: `conda install -c conda-forge
interpolation`

**Comment by natashawatkins** [comment]
Ok I installed via conda-forge and still got the same error

![image](https://user-images.githubusercontent.com/21038129/46415212-c4be6f00-c6f2-11e8-820a-2aff7b6627ec.png)

**Comment by albop** [comment]
Thank you @natashawatkins . But in order to understand the problem, I need to see the code where the function `interp` is being called. This is not apparent in the example you supply. Can you point me to the source ?

**Comment by natashawatkins** [comment]
In this notebook here: https://github.com/jstac/jitting_py_lectures/blob/master/lucas_model.ipynb

**Comment by albop** [comment]
Thanks, let me have a look.

**Comment by albop** [comment]
So this comes from the extrapolation behaviour of `np.interp` and `interpolation.interp`. The former uses a constant equal to the nearest value on the grid, while the latter extrapolates linearly (see graph).
Apparently this causes the convergence failure of the iterations, maybe by causing negative values.
![extrapolation](https://user-images.githubusercontent.com/276777/46419107-737fa100-c72d-11e8-9b57-df82a8b44fa4.png)

There are plans for a flexible extrapolation system, but in the meantime I'll commit a small change so that interp works with constant extrapolation and matches better default options of np.interp

**Comment by natashawatkins** [comment]
Thanks!!
